### ISSUE TITLE
[Bug] Not able to navigate to KDS. Not redirecting to the login page. 

### ISSUE THREAD

**Issue by bizmapNikhil** [ury-erp/mosaic#1]
**Issue Description:**
When a user is logged in and attempts to navigate to production unit pages with URL /URYMosaic/<production_unit> it fails to redirect to the expected production unit page. Instead, it redirects to login attempt page and renders the same page without redirecting. This behavior prevents users from accessing the appropriate pages after logging in successfully.

**Steps to Reproduce:**

1.  Log in to the URY app with valid credentials.
2. Attempt to navigate to a production unit page within the app (e.g., settings, profile, etc.).
3. Observe that the app does not redirect to the expected user authentication page.
4. Instead, the app remains on the same page without redirecting, preventing access to the intended page.

**Additional Information:**

1. This issue occurs consistently across different browsers and devices.
2. No errors or warnings are displayed in the browser console when the issue occurs.

**Screenshots**
1. Production Unit
![Screenshot 2024-04-09 123500](https://github.com/ury-erp/mosaic/assets/79086875/275f7197-59f3-44cc-9497-903dc24c339f)

2. Bug
![chrome-capture-2024-4-9 (2)](https://github.com/ury-erp/mosaic/assets/79086875/2b256977-8ad2-4372-9c00-74d6b9feb908)

**Comment by bizmapNikhil** [comment]
@jabir-tridz please give me solution on this

**Comment by wildman-web** [comment]
Is it solved?

**Comment by bizmapNikhil** [comment]
No not yet. Can you please help me out with this

**Comment by jezlan-tridz** [comment]
Hi @bizmapNikhil ,
To help us better understand and resolve the issue, please provide more details. Specifically:

1. Are you running the site on localhost?
2. Which version of Frappe and ERPNext are you using?

These details will help us diagnose the problem more accurately. Thank You

**Comment by bizmapNikhil** [comment]
HI @jezlan-tridz  
I was running the site on server and using the frappe 14.x and ERPNext 14.x versions and the same i tried on version 15 as well.

**Comment by jezlan-tridz** [comment]
Resolved : **"Not able to navigate to KDS. Not redirecting to the login page. "** (ab1c35b01d80d61f443007d06056aa18fb7aae8c)

**Comment by SahilmiyaKadri** [comment]
The issue is still exist 

![Screenshot_2024-08-29-13-31-01-491_com android chrome](https://github.com/user-attachments/assets/c1264afe-969a-49a2-bd62-ebaeef903c41)

**Comment by SaQDS** [comment]
This is authentication issue between http and https(ury and erpnext) . I had same issue and investigated a lot, and suddenly found the issue, please add ssl ca to your site with domain then login issue can be resolved. 
You can look on web console, you may find out error message there. 
But I have another issue on my qz printer as its uses unsecure ws, after https it will ask secure web socket. Still fighting 😂.
